// Server-side verification of a Cloudflare Turnstile token. Turnstile is
// Cloudflare's invisible captcha — the client widget produces a token,
// the server posts it to siteverify with the secret key to confirm it
// was generated by a real interaction.
//
// In environments without TURNSTILE_SECRET_KEY (local dev, tests) the
// verifier is permissive — it returns ok=true so the suggest flow stays
// exercisable end-to-end. Production must set the secret; the verify
// route will then enforce it.

const VERIFY_URL =
  "https://challenges.cloudflare.com/turnstile/v0/siteverify";

export interface TurnstileResult {
  ok: boolean;
  reason?: string;
}

export async function verifyTurnstile(
  token: string | undefined | null,
  remoteIp?: string,
): Promise<TurnstileResult> {
  const secret = process.env.TURNSTILE_SECRET_KEY;
  if (!secret) {
    // Permissive in dev / CI so the rest of the suggest flow can be
    // exercised without a real Cloudflare project.
    return { ok: true, reason: "no-secret-configured" };
  }
  if (!token) return { ok: false, reason: "missing-token" };

  const body = new URLSearchParams();
  body.set("secret", secret);
  body.set("response", token);
  if (remoteIp) body.set("remoteip", remoteIp);

  try {
    const r = await fetch(VERIFY_URL, {
      method: "POST",
      body,
      signal: AbortSignal.timeout(8000),
    });
    if (!r.ok) return { ok: false, reason: `siteverify-http-${r.status}` };
    const data = (await r.json()) as { success?: boolean; "error-codes"?: string[] };
    if (data.success) return { ok: true };
    return {
      ok: false,
      reason: (data["error-codes"] ?? ["unknown"]).join(","),
    };
  } catch (err) {
    return {
      ok: false,
      reason: err instanceof Error ? err.message : "fetch-failed",
    };
  }
}
